### ISSUE TITLE
Docs and website aren't consistent in how many tokens are needed to join a pool

### ISSUE THREAD

**Issue by PascalDierich** [balancer/docs-v1#7]
On the [websites](https://balancer.finance) landing page it says: `Join a multi-token pool with a single asset`, but in the [docs](https://docs.balancer.finance/getting-started/use-cases) it says: `Anyone with two or more ERC20 tokens can be a liquidity provider.`.

As far as I understand it joining a (2 token) pool with a single token means basically buying the other token with half (or whatever the ratio is) the provided liquidity and afterwards joining the pool. 

Anyway I think this inconsistency raises uncertainty for new users and should be addressed somehow.

**Comment by mikemcdonald** [comment]
Thanks, updated
